version: "2.1"
services:
  imager:
    build: .
    expose:
      - 8080
    ports:
      - 4000:80
      - 8081:8081
    environment:
      UDEV_LISTEN: 0.0.0.0:8080
  udev:
    build: .
    privileged: true
    links:
      - imager
    environment:
      UDEV_LISTEN: imager:8080
    volumes: 
      - /dev/:/dev/
    command: ["udevd"]